# Generated by Django 4.1.4 on 2023-01-01 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='Title',
            new_name='title',
        ),
    ]
