# Generated by Django 4.1.4 on 2023-01-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentuser',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
