# Generated by Django 4.1.4 on 2023-01-01 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Icon',
            new_name='icon',
        ),
    ]
